/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GraphicPrimitivesPanel.java
 *
 * Created on Sep 8, 2009, 9:59:24 AM
 */

package gui.panels;

import java.awt.event.ActionListener;

/**
 *
 * @author dszama
 */
public class GraphicPrimitivesPanel extends javax.swing.JPanel {

    GraphicPrimitivesTableModel gptm = new GraphicPrimitivesTableModel();
    ActionListener actionListener;

    public GraphicPrimitivesPanel() {
        initComponents();
    }

    /** Creates new form GraphicPrimitivesPanel */
    public GraphicPrimitivesPanel(ActionListener actionListener) {
        this.actionListener = actionListener;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        scpPaneGraphicPrimitivesPanel = new javax.swing.JScrollPane();
        tblGraphicsPrimitive = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Primitivas Graficas"));

        scpPaneGraphicPrimitivesPanel.setAutoscrolls(true);

        tblGraphicsPrimitive.setModel(gptm);
        tblGraphicsPrimitive.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scpPaneGraphicPrimitivesPanel.setViewportView(tblGraphicsPrimitive);

        btnDelete.setText("Borrar primitiva");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, tblGraphicsPrimitive, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), btnDelete, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        btnDelete.addActionListener(actionListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
            .addComponent(scpPaneGraphicPrimitivesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(scpPaneGraphicPrimitivesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane scpPaneGraphicPrimitivesPanel;
    private javax.swing.JTable tblGraphicsPrimitive;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public GraphicPrimitivesTableModel getGraphicPrimitivesTableModel() {
        return gptm;
    }

    public void dataChanged() {
        gptm.fireTableDataChanged();
        scpPaneGraphicPrimitivesPanel.getVerticalScrollBar().setValue(
                scpPaneGraphicPrimitivesPanel.getMaximumSize().height);
    }

    public void refresh() {
        repaint();
    }

    /**
     * @return the tblGraphicsPrimitive
     */
    public javax.swing.JTable getTblGraphicsPrimitive() {
        return tblGraphicsPrimitive;
    }

    /**
     * @param tblGraphicsPrimitive the tblGraphicsPrimitive to set
     */
    public void setTblGraphicsPrimitive(javax.swing.JTable tblGraphicsPrimitive) {
        this.tblGraphicsPrimitive = tblGraphicsPrimitive;
    }

    public void clean() {
        GraphicPrimitivesTableModel gptm = new GraphicPrimitivesTableModel();
    }
    
}
