/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PropertiesPanel.java
 *
 * Created on Sep 8, 2009, 9:42:49 AM
 */

package gui.panels;

import graphics.primitives.GraphicPrimitive;
import javax.swing.JTable;

/**
 *
 * @author dszama
 */
public class PropertiesPanel extends javax.swing.JPanel  {
    private GraphicPrimitive graphicPrimitive;
    /** Creates new form PropertiesPanel */
    public PropertiesPanel() {
        super();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpTblProperties = new javax.swing.JScrollPane();
        tblProperties = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Propiedades"));

        tblProperties.setModel(new PropertiesPanelTableModel());
        tblProperties.setGridColor(new java.awt.Color(204, 204, 204));
        scpTblProperties.setViewportView(tblProperties);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpTblProperties, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scpTblProperties, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scpTblProperties;
    private javax.swing.JTable tblProperties;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the graphicPrimitive
     */
    public GraphicPrimitive getGraphicPrimitive() {
        return graphicPrimitive;
    }

    /**
     * @param graphicPrimitive the graphicPrimitive to set
     */
    public void setGraphicPrimitive(GraphicPrimitive graphicPrimitive) {
        this.graphicPrimitive = graphicPrimitive;
        ((PropertiesPanelTableModel)tblProperties.getModel()).setGraphicPrimitive(graphicPrimitive);
        this.dataChanged();
    }

    public void dataChanged() {
        ((PropertiesPanelTableModel)tblProperties.getModel()).fireTableDataChanged();
    }

    public JTable getPropertiesTable() {
        return tblProperties;
    }

    public void clean() {
        setGraphicPrimitive(null);
    }

}
